# Generated by Django 3.2.9 on 2022-03-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_city_safarlar_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safarlar',
            old_name='c',
            new_name='city',
        ),
        migrations.AddField(
            model_name='safarlar',
            name='text',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safarlar',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='safarlar',
            name='video',
            field=models.FileField(upload_to='Safarlar/'),
        ),
        migrations.DeleteModel(
            name='SafarText',
        ),
    ]
